#!/usr/bin/env python3
"""dur2c.py IN.dur OUT.h — convert a durdraw .dur (gzipped JSON) into an
RLE C header for the xblackhole loop player. Deterministic output.

Cell model: density 0-6 (' ' . · ░ ▒ ▓ █) +
xterm-256 foreground color, run-length encoded as (count, density,
color-index) byte triples per frame.

NOTE the .dur layout quirk (verified against the real file): frame
"contents" is indexed [row][col] but "colorMap" is indexed [col][row].
"""
import gzip
import json
import sys

DENSITY = {' ': 0, '.': 1, '·': 2, '░': 3, '▒': 4,
           '▓': 5, '█': 6}

CUBE = (0, 95, 135, 175, 215, 255)
BASE16 = (0x000000, 0x800000, 0x008000, 0x808000, 0x000080, 0x800080,
          0x008080, 0xc0c0c0, 0x808080, 0xff0000, 0x00ff00, 0xffff00,
          0x0000ff, 0xff00ff, 0x00ffff, 0xffffff)


def xterm_rgb(n):
    if n < 16:
        return BASE16[n]
    if n < 232:
        n -= 16
        r, g, b = CUBE[n // 36], CUBE[(n // 6) % 6], CUBE[n % 6]
        return (r << 16) | (g << 8) | b
    v = 8 + 10 * (n - 232)
    return (v << 16) | (v << 8) | v


def main(inpath, outpath):
    with gzip.open(inpath, 'rt', encoding='utf-8') as fh:
        movie = json.load(fh)["DurMovie"]
    cols, lines = movie["columns"], movie["lines"]
    frames = movie["frames"]

    # Only colors actually painted matter: density-0 (blank) cells always
    # render black regardless of their colorMap entry (see main.c), so
    # including their color would inflate NCOLORS with unused entries.
    used = set()
    for f in frames:
        contents, cmap = f["contents"], f["colorMap"]
        for y in range(lines):
            row = contents[y]
            if not isinstance(row, str):
                row = "".join(row)
            for x in range(cols):
                ch = row[x] if x < len(row) else ' '
                if DENSITY.get(ch, 6) != 0:
                    used.add(cmap[x][y][0])
    used = sorted(used)
    cindex = {c: i for i, c in enumerate(used)}
    if len(used) > 255:
        sys.exit("dur2c: more than 255 distinct colors")

    runs = bytearray()
    offsets = [0]
    for f in frames:
        contents, cmap = f["contents"], f["colorMap"]
        prev, count = None, 0
        for y in range(lines):
            row = contents[y]
            if not isinstance(row, str):
                row = "".join(row)
            for x in range(cols):
                ch = row[x] if x < len(row) else ' '
                d = DENSITY.get(ch, 6)
                col = cindex[cmap[x][y][0]] if d else 0
                cell = (d, col)
                if cell == prev and count < 255:
                    count += 1
                else:
                    if prev is not None:
                        runs.extend((count, prev[0], prev[1]))
                    prev, count = cell, 1
        runs.extend((count, prev[0], prev[1]))
        offsets.append(len(runs))

    with open(outpath, 'w', encoding='utf-8') as out:
        out.write("/* generated by dur2c.py — do not edit */\n")
        out.write("enum { FRAME_W = %d, FRAME_H = %d, NFRAMES = %d, "
                  "NCOLORS = %d };\n" % (cols, lines, len(frames), len(used)))
        out.write("static const unsigned long dur_colors[NCOLORS] = {\n")
        for c in used:
            out.write("    0x%06x,\n" % xterm_rgb(c))
        out.write("};\n")
        out.write("static const unsigned char dur_runs[] = {\n")
        for i in range(0, len(runs), 12):
            out.write("    " + ",".join(str(b) for b in runs[i:i + 12]) + ",\n")
        out.write("};\n")
        out.write("static const unsigned int dur_frame_off[NFRAMES + 1] = "
                  "{ " + ", ".join(str(o) for o in offsets) + " };\n")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: dur2c.py IN.dur OUT.h")
    main(sys.argv[1], sys.argv[2])
