#!/usr/bin/env bash
# Wallpaper subsystem: writes the launcher script and wires it into ~/.xinitrc
# inside a marked, idempotent block.

WP_BLOCK_START="# >>> manjaro-sl wallpaper >>>"
WP_BLOCK_END="# <<< manjaro-sl wallpaper <<<"

ly_animation_to_wallpaper() {
  case "$1" in
    doom)   echo doomfire ;;
    matrix) echo xmatrix ;;
    *)      echo none ;;   # colormix is a phase-3 stub
  esac
}

wallpaper_write_launcher() {
  local wp="$1" dir="$HOME/.config/manjaro-sl" f
  f="$dir/wallpaper.sh"
  mkdir -p "$dir"
  cat > "$f" <<EOF
#!/usr/bin/env bash
# Generated by manjaro-sl — starts the desktop wallpaper animation.
exec $wp
EOF
  chmod 755 "$f"
}

wallpaper_strip_block() {
  local xi="$HOME/.xinitrc"
  [ -f "$xi" ] || return 0
  sed -i "\|^${WP_BLOCK_START}\$|,\|^${WP_BLOCK_END}\$|d" "$xi"
}

wallpaper_wire_xinitrc() {
  local xi="$HOME/.xinitrc"
  wallpaper_strip_block
  touch "$xi"
  # Insert before an 'exec dwm' line if present, else append.
  local block
  block=$(printf '%s\n%s\n%s' "$WP_BLOCK_START" \
    "\"\$HOME/.config/manjaro-sl/wallpaper.sh\" &" "$WP_BLOCK_END")
  if grep -q '^exec .*dwm' "$xi"; then
    # The rewrite must keep the original mode: Ly executes ~/.xinitrc as a
    # program, so losing the +x bit locks the user out of their session.
    local mode; mode=$(stat -c '%a' "$xi")
    awk -v blk="$block" '!done && /^exec .*dwm/ { print blk; done=1 } { print }' \
      "$xi" > "$xi.tmp" && mv "$xi.tmp" "$xi"
    chmod "$mode" "$xi"
  else
    [ -s "$xi" ] && [ -n "$(tail -c1 "$xi")" ] && printf '\n' >> "$xi"
    printf '%s\n' "$block" >> "$xi"
  fi
}

wallpaper_apply() {
  local wp; wp=$(state_get dwm/wallpaper)
  if [ "$wp" = "none" ] || [ -z "$wp" ] || [ "$wp" = "off" ]; then
    wallpaper_strip_block
    return 0
  fi
  wallpaper_write_launcher "$wp"
  wallpaper_wire_xinitrc
}
